import { useMemo, useState } from "react";

const STORAGE_KEY = "life-command-centre:phd:v1";
const COLORS = { bg: "#0B1020", card: "#111827", border: "#263247", text: "#E5E7EB", muted: "#94A3B8", blue: "#60A5FA", purple: "#A78BFA", green: "#34D399", amber: "#FBBF24", red: "#F87171" };
const INITIAL = { registrationDate: "", committeeStatus: "to_verify", committeeDate: "", milestones: { "phd-001":"to_verify", "phd-002":"completed", "phd-003":"completed", "phd-004":"completed", "phd-005":"completed", "phd-006":"to_verify", "phd-007":"active", "phd-008":"to_verify", "phd-009":"blocked", "phd-010":"to_verify", "phd-011":"to_verify", "phd-012":"blocked", "phd-013":"blocked", "phd-014":"blocked", "phd-015":"blocked", "phd-016":"not_started", "phd-017":"not_started" } };
const MILESTONES = [
  ["phd-001","Registration","compliance","Root anchor for all regulatory dates."],["phd-002","Supervisor Assignment","research","Supervisor relationship established."],["phd-003","Broad Research Ideology","research","Human-Centered Multimodal Explainable AI Framework with Wearable Sensors for Special Needs Children."],["phd-004","Keyword Extraction","research","25 keywords documented; supervisor requested 15–20."],["phd-005","Problem Statement Narrowing","research","10 problem statements scoped (PS-1 through PS-10)."],["phd-006","Dataset Requirements","research","Confirm whether all 10 PS have dataset requirements."],["phd-007","Primary Problem Statement Selection","research","Current critical-path item; must be locked before the research timeline."],["phd-008","Doctoral Committee Formation","compliance","3-week window is computed only after registration is confirmed."],["phd-009","4-Year Month-by-Month Timeline","research","Supervisor-requested artifact; blocked until primary PS is locked."],["phd-010","Coursework — 4 courses / 12 credits","compliance","Academic-compliance track from registration."],["phd-011","CGPA Threshold","compliance","Eligibility gate for the Comprehensive Examination."],["phd-012","Comprehensive Examination","compliance","Blocked until coursework and CGPA eligibility are known."],["phd-013","Research Milestones","research","Module-by-module execution against the locked PS."],["phd-014","Publications — 2 required","research","Long-lead gate before synopsis; keep visible while blocked."],["phd-015","Synopsis","research","Depends on the publication gate."],["phd-016","Thesis","research","Downstream of synopsis."],["phd-017","Viva","research","Must fit inside the maximum regulatory envelope."]
].map(([id,title,track,note])=>({id,title,track,note}));
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return INITIAL;const p=JSON.parse(raw);return {...INITIAL,...p,milestones:{...INITIAL.milestones,...p.milestones}}}catch{return INITIAL}}
function saveState(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
function addMonths(s,m){if(!s)return null;const d=new Date(`${s}T00:00:00`);if(Number.isNaN(d.getTime()))return null;d.setMonth(d.getMonth()+m);return d}
function fmt(d){return d?new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"Not confirmed"}
function risk(id,state){if(["phd-001","phd-008","phd-010","phd-011"].includes(id))return["unassessable","Required fact is still TO-VERIFY."];if(id==="phd-007")return["at_risk","Primary problem statement is still being finalized."];if(state.milestones[id]==="blocked")return["unassessable","Upstream dependency is not yet cleared."];return["on_track","No date-based breach can be computed from the current known facts."]}
function Badge({children,tone="blue"}){return <span style={{border:`1px solid ${COLORS[tone]}55`,color:COLORS[tone],background:`${COLORS[tone]}14`,borderRadius:999,padding:"3px 8px",fontSize:10,fontWeight:800}}>{children}</span>}
export default function PhdCommandCenter(){const[state,setState]=useState(loadState);const[open,setOpen]=useState(false);const[filter,setFilter]=useState("all");const[selected,setSelected]=useState(null);const patch=n=>{const s={...state,...n};setState(s);saveState(s)};const verification=useMemo(()=>MILESTONES.filter(m=>["phd-001","phd-006","phd-008","phd-010","phd-011"].includes(m.id)),[]);const visible=useMemo(()=>MILESTONES.filter(m=>filter==="all"||m.track===filter),[filter]);const min=addMonths(state.registrationDate,36),max=addMonths(state.registrationDate,72),reg=state.registrationDate?new Date(`${state.registrationDate}T00:00:00`):null,committee=reg?new Date(reg.getTime()+21*86400000):null,breach=committee&&!state.committeeDate&&committee<new Date();return <>
<button onClick={()=>setOpen(true)} aria-label="Open PhD Command Centre" style={{position:"fixed",right:18,bottom:18,zIndex:9998,border:`1px solid ${COLORS.purple}66`,background:`linear-gradient(135deg,${COLORS.purple},#6366F1)`,color:"white",borderRadius:999,padding:"11px 15px",fontWeight:900,cursor:"pointer",boxShadow:"0 10px 35px #0008"}}>🎓 PhD Command Centre</button>
{open&&<div style={{position:"fixed",inset:0,zIndex:9999,background:"#020617cc",backdropFilter:"blur(8px)",display:"flex",justifyContent:"flex-end"}}><div style={{width:"min(720px,100vw)",height:"100%",overflow:"auto",background:COLORS.bg,color:COLORS.text,padding:18,fontFamily:"system-ui,sans-serif"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><div style={{fontSize:20,fontWeight:900}}>🎓 PhD Command Centre</div><div style={{color:COLORS.muted,fontSize:12}}>Regulatory truth layer · no fabricated dates</div></div><button onClick={()=>setOpen(false)} style={{background:"transparent",color:COLORS.text,border:`1px solid ${COLORS.border}`,borderRadius:8,padding:"7px 10px",cursor:"pointer"}}>✕</button></div>
<div style={{border:`1px solid ${COLORS.amber}55`,background:`${COLORS.amber}0D`,borderRadius:14,padding:14,marginBottom:14}}><div style={{fontWeight:900,color:COLORS.amber}}>⚠️ Needs verification</div><div style={{fontSize:12,color:COLORS.muted,marginTop:4}}>Unknown facts stay visible until explicitly confirmed.</div><div style={{display:"grid",gap:8,marginTop:10}}>{verification.map(m=><div key={m.id} style={{display:"flex",justifyContent:"space-between",gap:8,borderTop:`1px solid ${COLORS.border}`,paddingTop:8}}><span>{m.id} · {m.title}</span><Badge tone="amber">TO-VERIFY</Badge></div>)}</div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:14}}><label style={{border:`1px solid ${COLORS.border}`,borderRadius:12,padding:12,fontSize:11,color:COLORS.muted}}>Registration date<input type="date" value={state.registrationDate} onChange={e=>patch({registrationDate:e.target.value})} style={{display:"block",width:"100%",marginTop:7,background:COLORS.card,color:COLORS.text,border:`1px solid ${COLORS.border}`,borderRadius:8,padding:8}}/></label><label style={{border:`1px solid ${COLORS.border}`,borderRadius:12,padding:12,fontSize:11,color:COLORS.muted}}>Doctoral Committee status<select value={state.committeeStatus} onChange={e=>patch({committeeStatus:e.target.value})} style={{display:"block",width:"100%",marginTop:7,background:COLORS.card,color:COLORS.text,border:`1px solid ${COLORS.border}`,borderRadius:8,padding:8}}><option value="to_verify">TO-VERIFY</option><option value="started">Formation started</option><option value="formed">Formed</option><option value="not_formed">Not formed</option></select>{state.committeeStatus==="formed"&&<input type="date" value={state.committeeDate} onChange={e=>patch({committeeDate:e.target.value})} style={{display:"block",width:"100%",marginTop:7,background:COLORS.card,color:COLORS.text,border:`1px solid ${COLORS.border}`,borderRadius:8,padding:8}}/>}</label></div>
<div style={{border:`1px solid ${COLORS.purple}44`,background:`${COLORS.purple}0D`,borderRadius:14,padding:14,marginBottom:14}}><div style={{fontWeight:900,color:COLORS.purple}}>Regulatory envelope</div>{!reg?<div style={{marginTop:8,color:COLORS.muted,fontSize:12}}>Registration date not confirmed — regulatory clock cannot be displayed.</div>:<><div style={{display:"flex",justifyContent:"space-between",marginTop:8,fontSize:12}}><span>Minimum: {fmt(min?.toISOString().slice(0,10))}</span><span>Maximum: {fmt(max?.toISOString().slice(0,10))}</span></div><div style={{height:8,background:"#1E293B",borderRadius:99,overflow:"hidden",marginTop:8}}><div style={{width:`${Math.min(100,Math.max(0,((Date.now()-reg)/(max-reg))*100))}%`,height:"100%",background:COLORS.purple}}/></div></>}<div style={{marginTop:10,fontSize:12,color:breach?COLORS.red:COLORS.muted}}>{committee?`Doctoral Committee window: ${fmt(committee.toISOString().slice(0,10))}`:"Doctoral Committee window: waiting for registration date"}{breach?" · POSSIBLE BREACH — verify immediately":""}</div></div>
<div style={{display:"flex",gap:7,marginBottom:12}}>{["all","research","compliance"].map(x=><button key={x} onClick={()=>setFilter(x)} style={{background:filter===x?COLORS.blue:"transparent",color:filter===x?"#06111F":COLORS.muted,border:`1px solid ${filter===x?COLORS.blue:COLORS.border}`,borderRadius:999,padding:"6px 10px",fontWeight:800,cursor:"pointer",textTransform:"capitalize"}}>{x}</button>)}</div>
<div style={{display:"grid",gap:8}}>{visible.map(m=>{const[r,reason]=risk(m.id,state),status=state.milestones[m.id];return <button key={m.id} onClick={()=>setSelected(m)} style={{textAlign:"left",border:`1px solid ${r==="at_risk"?COLORS.red+"66":COLORS.border}`,background:COLORS.card,borderRadius:12,padding:12,color:COLORS.text,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><span style={{fontWeight:900}}>{m.id} · {m.title}</span><Badge tone={status==="completed"?"green":r==="at_risk"?"red":r==="unassessable"?"amber":"blue"}>{status.replace("_"," ").toUpperCase()}</Badge></div><div style={{color:COLORS.muted,fontSize:11,marginTop:5}}>{m.track==="research"?"Research track":"Academic-compliance track"} · {reason}</div></button>})}</div>
{selected&&<div style={{position:"fixed",inset:0,background:"#02061799",display:"grid",placeItems:"center",padding:18}} onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} style={{width:"min(560px,100%)",background:COLORS.card,border:`1px solid ${COLORS.border}`,borderRadius:16,padding:18}}><div style={{fontSize:18,fontWeight:900}}>{selected.id} · {selected.title}</div><p style={{color:COLORS.muted,fontSize:12,lineHeight:1.5,margin:"8px 0 14px"}}>{selected.note}</p><label style={{color:COLORS.muted,fontSize:11}}>Status<select value={state.milestones[selected.id]} onChange={e=>patch({milestones:{...state.milestones,[selected.id]:e.target.value}})} style={{display:"block",width:"100%",marginTop:6,background:COLORS.bg,color:COLORS.text,border:`1px solid ${COLORS.border}`,borderRadius:8,padding:9}}><option value="to_verify">TO-VERIFY</option><option value="not_started">Not started</option><option value="active">Active</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><button onClick={()=>setSelected(null)} style={{marginTop:14,background:COLORS.blue,color:"#06111F",border:0,borderRadius:8,padding:"8px 14px",fontWeight:900,cursor:"pointer"}}>Save & close</button></div></div>}
</div></div>}
</>}
